### ISSUE TITLE
How to apply Kitti to centerfusion.

### ISSUE THREAD

**Issue by Nerdmust** [mrnabati/CenterFusion#11]
Thank you very much for your work. It's a great job. I have a dataset, but this data is similar to Kitti's format. How to apply it to centerfusion?

**Comment by mrnabati** [comment]
I have not tested the code for any other dataset format except NuScenes, but you should be able to modify the code to make it work with your dataset. The first step would be converting Kitti to COCO format, and making sure the radar point clouds are added to the `image_info` dictionary. You can use and modify the [convert_kitti_to_coco.py](https://github.com/xingyizhou/CenterNet/blob/master/src/tools/convert_kitti_to_coco.py) script from CenterNet to do that. This is to make sure the [_load_pc_data()](https://github.com/mrnabati/CenterFusion/blob/616dcda9464c17f98b1550ea8a212bce30eba1aa/src/lib/dataset/generic_dataset.py#L132) function in the [generic_dataset.py](https://github.com/mrnabati/CenterFusion/blob/616dcda9464c17f98b1550ea8a212bce30eba1aa/src/lib/dataset/generic_dataset.py) script can read the radar point cloud.

**Comment by UmangBDhanani** [comment]
Hello @Nerdmust . Have you have any success in converting the Kitti dataset into COCO format to use the centerfusion algorithm? Any help would be appreciated. Thank you.

**Comment by UmangBDhanani** [comment]
> I have not tested the code for any other dataset format except NuScenes, but you should be able to modify the code to make it work with your dataset. The first step would be converting Kitti to COCO format, and making sure the radar point clouds are added to the `image_info` dictionary. You can use and modify the [convert_kitti_to_coco.py](https://github.com/xingyizhou/CenterNet/blob/master/src/tools/convert_kitti_to_coco.py) script from CenterNet to do that. This is to make sure the [_load_pc_data()](https://github.com/mrnabati/CenterFusion/blob/616dcda9464c17f98b1550ea8a212bce30eba1aa/src/lib/dataset/generic_dataset.py#L132) function in the [generic_dataset.py](https://github.com/mrnabati/CenterFusion/blob/616dcda9464c17f98b1550ea8a212bce30eba1aa/src/lib/dataset/generic_dataset.py) script can read the radar point cloud.

Hello @mrnabati, @Nerdmust . Can we use the same generic_dataset.py file if we want to use the dataset similar to KITTI dataset
