### ISSUE TITLE
error: command 'g++' failed with exit status 1

### ISSUE THREAD

**Issue by DonMuv** [mrnabati/CenterFusion#14]
when Build the deformable convolution library
error: command 'g++' failed with exit status 1

**Comment by xiyangyang123** [comment]
u can use cuda 10.2 and pytorch 1.4. higher pytroch version is suitable for DCN

**Comment by albertchristian92** [comment]
are you use Docker?

**Comment by xiyangyang123** [comment]
no

Albert Christian <notifications@github.com> 于2021年1月11日周一 下午4:46写道：
