### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by DonMuv** [mrnabati/CenterFusion#15]
CUDA out of memory
My GPU memory is 11G
and whatever the batch_size is 
also CUDA out of memory
help me

**Comment by albertchristian92** [comment]
Did you solve this one? I also met the same problem

**Comment by mrnabati** [comment]
Make sure you set the `CUDA_VISIBLE_DEVICES` and `--gpus` parameter in the train and test scripts correctly. These parameters are currently set to work with two GPUs.
