### ISSUE TITLE
Running demo with Image+Radar data

### ISSUE THREAD

**Issue by RameshSena** [mrnabati/CenterFusion#18]
Hi, Could you please point me on how to run demo.py with both image and Radar data. I was able to run the demo.py with images and video files but I was wondering how to incorporate radar data as well.

On an additional note could you please help me on how to use kitti dataset with Image and Lidar data instead of Radar and how to convert Lidar to COCO format.

**Comment by mrnabati** [comment]
The demo is not currently available with CenterFusion. The existing demo script is from CenterNet and has not been adapted to CenterFusion yet. 
The Kitti dataset does not provide Radar point clouds, and CenterFusion is a Radar-Camera sensor fusion algorithm. Modifying CenterFusion to use Lidar point clouds instead is not straight forward, as radar point clouds have different attributes used by CenterFusion that are not available in Lidar point clouds.
