### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by albertchristian92** [mrnabati/CenterFusion#19]
Hi, Thank you for your works. Actually, I am interested in this works, but when I tried to start training your code using Docker, I met a problem RuntimeError: CUDA error: out of memory as shown here:
![outofmemory](https://user-images.githubusercontent.com/12479762/104159554-81531f00-542a-11eb-9a9e-48381f5f151e.PNG)

I am using Multi GPU GeForce GTX 1080 as following:
![nvidia-smi](https://user-images.githubusercontent.com/12479762/104159566-86b06980-542a-11eb-835b-b328a1869e9e.PNG)

Here, how I run your code:

python3 main.py \
    ddd \
    --exp_id centerfusion \
    --shuffle_train \
    --train_split mini_train \
    --val_split mini_val \
    --val_intervals 1 \
    --run_dataset_eval \
    --nuscenes_att \
    --velocity \
    --batch_size 4 \
    --lr 2.5e-4 \
    --num_epochs 60 \
    --lr_step 50 \
    --save_point 20,40,50 \
    --gpus 0,2,3 \
    --not_rand_crop \
    --flip 0.5 \
    --shift 0.1 \
    --pointcloud \
    --radar_sweeps 6 \
    --pc_z_offset 0.0 \
    --pillar_dims 1.0,0.2,0.2 \
    --max_pc_dist 60.0 \
    --num_workers 0 \
   --load_model ../models/centerfusion_e60.pth \

Please give any suggestion regarding this issue. Thank you very much.

**Comment by fabrizioschiano** [comment]
Hi @albertchristian92 , how did you solve this problem?
