### ISSUE TITLE
Visualization results

### ISSUE THREAD

**Issue by unter-dev** [mrnabati/CenterFusion#25]
when i run test.py with mini_val,i can only get an evaluation,but how can i get a Visualization results ?

**Comment by Tracy-Baker** [comment]
hi，I have the same problem now, did you find the solution ?

**Comment by Liaoqing-up** [comment]
me too

**Comment by mrnabati** [comment]
Please refer to [this issue](https://github.com/mrnabati/CenterFusion/issues/39)
