### ISSUE TITLE
Using a subset of the nuScenes for training and validation

### ISSUE THREAD

**Issue by ngowilliam1** [mrnabati/CenterFusion#28]
I am trying to train and evaluate centerfusion on the subset of the data, more specifically, using exclusively v1.0-trainval01_blobs.tgz.

I understood that I needed to modify the convert_nuScenes.py script to make my train/val scenes match up with the scenes present in trainval01_blobs.
![image](https://user-images.githubusercontent.com/46735044/111814386-c7a47e80-88b0-11eb-80be-7bfc4ef7adf6.png)

Training was no issue, but evaluation is where I get an issue.

`Traceback (most recent call last):
  File "tools/nuscenes-devkit/python-sdk/nuscenes/eval/detection/evaluate.py", line 305, in <module>
    output_dir=output_dir_, verbose=verbose_)
  File "tools/nuscenes-devkit/python-sdk/nuscenes/eval/detection/evaluate.py", line 89, in __init__
    "Samples in split doesn't match samples in predictions."
AssertionError: Samples in split doesn't match samples in predictions.
`
Any idea what could be causing issue?

**Comment by mrnabati** [comment]
To do that you'll also need to modify the nuScenes evaluation code to include your new train/val splits. Specifically, you need to modify the [splits.py](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/splits.py) file to include your new splits. Also you need to use different names for your splits, so the evaluation code doesn't confuse them with the original `train` and `val` splits defined there. Hope that helps.

**Comment by Balazizo** [comment]
Hello @ngowilliam1, I'm struggling with the same problem. Can you please tell me how you solved the issue? I copied my new train/val splits from the convert_nuScenes.py script and overwrote the the train/val splits in splits.py to match the splits. However, the problem wasn't solved. If you remember how you solved it, can you please tell me what more I should do? I would be very grateful.

**Comment by programmeeer** [comment]
Can you share code necessary to use partial nuscenes dataset.? both training and testing.

**Comment by fabrizioschiano** [comment]
@programmeeer , I would be interested in this too. Did you find a solution?

**Comment by fabrizioschiano** [comment]
I would be interested in knowing more specifically how @ngowilliam1 (or @programmeeer) solved this problem. Thanks!

**Comment by Aniket-Gujarathi** [comment]
Hi, I am facing the same issue as @ZiadElmassik  described above. Can you please explain how you got the evaluation working for the subset of the data. I too copied my splits (for mini-train and mini-val) and replaced the splits provided in the splits.py file, but still get the same error.

Thank you.
