### ISSUE TITLE
change model

### ISSUE THREAD

**Issue by AHappyFlyBird** [mrnabati/CenterFusion#29]
Hi! friend，I need your help. When I try test.sh , I change the model from centerfusion modle to nuscens_3Ddetection_e140 model,like the picture:
![image](https://user-images.githubusercontent.com/69776408/111906509-cbd8c380-8a8b-11eb-9262-ed788637f8e2.png)
But the result like this
![image](https://user-images.githubusercontent.com/69776408/111906719-fc6d2d00-8a8c-11eb-8489-2dd31fdceb8d.png)
,the error is too big,Is this a normal result?OR,  Is there any parameters that I need to change or add

**Comment by mrnabati** [comment]
Hi.
If you want to get the baseline CenterNet results you should run the CenterNet code. CenterFusion has many modifications and might not give you the correct CenterNet results even when modifying the test script options like what you've done.
