### ISSUE TITLE
DCNv2 & make.sh was not found in src/lib/model/networks

### ISSUE THREAD

**Issue by zyms5244** [mrnabati/CenterFusion#3]

**Comment by mrnabati** [comment]
That means the DCN submodule has not been downloaded. You can download it like this:
```
cd $CF_ROOT/src/lib/model/networks
git clone https://github.com/CharlesShang/DCNv2/
````
and then continue with the installation.

**Comment by fabrizioschiano** [comment]
I would also like to add that you might experience an error while running the `make.sh` . One possible solution is explained here: https://github.com/CharlesShang/DCNv2/issues/79#issuecomment-930125931
I hope that's helpful for someone else.
