### ISSUE TITLE
I was not able to evaluate test dataset.

### ISSUE THREAD

**Issue by harishank** [mrnabati/CenterFusion#30]
In nuscenes we have train, val and test dataset. when i tried to run 
**bash test.sh**  after setting **--val_split test.** 
i was getting this following error. so that i **couldno**t reproduce your results for test dataset.

Initializing nuScenes detection evaluation
Loaded results from /workspace/centerfusion_onlytest/src/lib/../../exp/ddd/centerfusion/results_nuscenes_det_test.json. Found detections for 6008 samples.
Loading annotations for test split from nuScenes version: v1.0-test
Traceback (most recent call last):
  File "tools/nuscenes-devkit/python-sdk/nuscenes/eval/detection/evaluate.py", line 301, in <module>
    output_dir=output_dir_, verbose=verbose_)
  File "tools/nuscenes-devkit/python-sdk/nuscenes/eval/detection/evaluate.py", line 82, in __init__
    self.gt_boxes = load_gt(self.nusc, self.eval_set, DetectionBox, verbose=verbose)
  File "/usr/local/lib/python3.7/dist-packages/nuscenes/eval/common/loaders.py", line 94, in load_gt
    'Error: You are trying to evaluate on the test set but you do not have the annotations!'
AssertionError: Error: You are trying to evaluate on the test set but you do not have the annotations!

**could you help me how to resolve this issue.**

**Comment by mrnabati** [comment]
You can not evaluate on the test set, because there is no ground truth data for that split. Despite that error, it should still generate the results file, which you can submit to the NuScenes benchmark server to be evaluated.
