### ISSUE TITLE
I have a minor question about the code.

### ISSUE THREAD

**Issue by 2gunsu** [mrnabati/CenterFusion#33]
Thank you so much for sharing your valuable research and code.
I am having a problem while training your model using the nuScenes dataset.

In lines 105-107 of the ```CenterFusion/src/main.py```,
(https://github.com/mrnabati/CenterFusion/blob/master/src/main.py#L105-L107)
```python
          # log dataset-specific evaluation metrics
          with open('{}/metrics_summary.json'.format(out_dir), 'r') as f:
            metrics = json.load(f)
```
it seems to load the **'metrics_summary.json'** file.
But I can't find the part where this file is created even after looking through the whole code.

I would really appreciate it if you could tell me about this.

**Comment by tiga-dudu** [comment]
> 非常感谢您分享您宝贵的研究和代码。我在使用 nuScenes 数据集训练模型时遇到问题。
> 
> 在第 105-107 行中，（https://github.com/mrnabati/CenterFusion/blob/master/src/main.py#L105-L107`CenterFusion/src/main.py`)
> 
> ```python
>           # log dataset-specific evaluation metrics
>           with open('{}/metrics_summary.json'.format(out_dir), 'r') as f:
>             metrics = json.load(f)
> ```
> 
> 它似乎加载**了“metrics_summary.json”**文件。但是即使浏览了整个代码，我也找不到创建此文件的部分。
> 
> 如果您能告诉我这件事，我将不胜感激。

请问你解决了吗
