### ISSUE TITLE
Can nuScenes-Mini be used to train?

### ISSUE THREAD

**Issue by qrzeffort** [mrnabati/CenterFusion#38]
When I trained with nuscene mini (5.4gb) according to the steps in readme, an error occurs:

 python convert_nuScenes.py

FileNotFoundError: [Errno 2] No such file or directory: '../../data/nuscenes/samples/RADAR_FRONT_RIGHT/n015-2018-07-18-11-07-57+0800__RADAR_FRONT_RIGHT__1531883530444336.pcd'

I later tried to add meta-trainval to the dataset, but it's useless.
Now,I am not sure what happened. Can someone give me some suggestions?
Thank you!

**Comment by fabrizioschiano** [comment]
@qrzeffort , what did you do that made you close the issue? Did you download the metadata folder and some of the file blobs? 
like in the following screenshot? 
![image](https://user-images.githubusercontent.com/3736380/135899179-4e1c3a19-e449-404f-8558-376a982708fc.png)

Did it work then?

**Comment by fabrizioschiano** [comment]
I solved this issue. You need to make sure that you extract:
- `v1.0-trainval01_blobs.tgz` (I am trying to use only a subset of the whole dataset), 
- `v1.0-mini.tgz` 
Then, you need to make sure that the folders `CenterFusion/data/nuscenes/samples` and `CenterFusion/data/nuscenes/sweeps` contain all the files from the folders `v1.0-mini/` and `v1.0-trainval01_blobs/`. 

Instead, I hade this error because, I had put the `sweeps` and `samples` only of the `v1.0-mini/` extracted folder.

**Comment by fabrizioschiano** [comment]
I now have the same issue with the `test` split. 

```
reordering images
val 5484 images 32721 boxes
out_path ../../data/nuscenes/annotations_6sweeps/val.json
Traceback (most recent call last):
  File "convert_nuScenes.py", line 340, in <module>
    main()
  File "convert_nuScenes.py", line 95, in main
    nusc = NuScenes(
  File "/home/fabrizioschiano/.virtualenvs/centerfusion/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 62, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: ../../data/nuscenes/v1.0-test
```

I am therefore downloading the related file
![image](https://user-images.githubusercontent.com/3736380/136040084-0fa7d189-0722-460e-924a-39db835f75e7.png)

**Comment by zhuyongWillem** [comment]
> I solved this issue. You need to make sure that you extract:
> 
> * `v1.0-trainval01_blobs.tgz` (I am trying to use only a subset of the whole dataset),
> * `v1.0-mini.tgz`
>   Then, you need to make sure that the folders `CenterFusion/data/nuscenes/samples` and `CenterFusion/data/nuscenes/sweeps` contain all the files from the folders `v1.0-mini/` and `v1.0-trainval01_blobs/`.
> 
> Instead, I hade this error because, I had put the `sweeps` and `samples` only of the `v1.0-mini/` extracted folder.

I have confirmed that the folders `CenterFusion/data/nuscenes/samples` and `CenterFusion/data/nuscenes/sweeps` contain all the files from the folders `v1.0-mini/` and `v1.0-trainval01_blobs/`.

However, I meet a new problem, FileNotFoundError: [Errno 2] No such file or directory: '../../data/nuscenes/samples/RADAR_FRONT_RIGHT/n015-2018-08-01-16-32-59+0800__RADAR_FRONT_RIGHT__1533112388227413.pcd'

Can you help me? thank you very much

**Comment by fabrizioschiano** [comment]
Hi @zhuyongWillem , it seems that you don't have the file `'../../data/nuscenes/samples/RADAR_FRONT_RIGHT/n015-2018-08-01-16-32-59+0800__RADAR_FRONT_RIGHT__1533112388227413.pcd'` in the correct folder. Are you sure that you extracted the files well as I pointed out [here](https://github.com/mrnabati/CenterFusion/issues/38#issuecomment-934448928)?

**Comment by zhuyongWillem** [comment]
![err](https://user-images.githubusercontent.com/66372983/142170035-8ad75779-3eed-498a-aeb5-db6dd587c9b1.JPG)

Yes, I‘m sure that I extracted the all files from 'v1.0-trainval01_blobs.tgz' and 'v1.0-mini.tgz', but still had FileNotFoundError. Can you share me your folders? 

Thank you very much

**Comment by fabrizioschiano** [comment]
Sorry for my late reply @zhuyongWillem 

Attached is a zip file with my folder structure

[tree_printed.zip](https://github.com/mrnabati/CenterFusion/files/7717321/tree_printed.zip)
