### ISSUE TITLE
Conversion to onnx

### ISSUE THREAD

**Issue by Amirtha1189** [mrnabati/CenterFusion#7]
Hi,

As mentioned in convert_to_onnx.py script, I couldnt convert to onnx with dcn layers. Is there a pretrained model available with conv layers instead of dcn.?

**Comment by mrnabati** [comment]
Hi. I have not tried to convert the model to onnx, and unfortunately do not have a pretrained model without dcn layers. There is a discussion about this issue [here](https://github.com/xingyizhou/CenterTrack/issues/3) that might be helpful for you.
