### ISSUE TITLE
how to export results like /figures/qualitative_results.jpg

### ISSUE THREAD

**Issue by vincentzhouwenqi** [mrnabati/CenterFusion#8]
i want to see some  visible results just like /figures/qualitative_results.jpg and pillars.png by using Pretrained Models.

which py document should i use ?

**Comment by mrnabati** [comment]
You can add the `--debug 4` to the arguments in the `train.sh` or `test.sh` scripts to enable the debugging mode and get the intermediate results. The debug images will be saved to `exp\ddd\debug`, and there will be a lot of them so you probably don't want to run it in the debug mode on the whole dataset.

**Comment by Balazizo** [comment]
Hello, when visualizing using debug 4, I can see the predicted bounding boxes. How do I also see the ground truth as in qualitative_results.jpg?

**Comment by fabrizioschiano** [comment]
> Hello, when visualizing using debug 4, I can see the predicted bounding boxes. How do I also see the ground truth as in qualitative_results.jpg?

Hi @Balazizo , did you manage to do that? i am also interested

**Comment by puyoulingdi** [comment]
Hi @fabrizioschiano, did you manage to do that? i am also interested

**Comment by puyoulingdi** [comment]
Hi @fabrizioschiano, did you manage to do that? i am also interested
