### ISSUE TITLE
Pretrained Models not accessible

### ISSUE THREAD

**Issue by umar052001** [mrnabati/CenterFusion#81]
Readme links to both pretrained models is expired. Please update them, Thanks!
![image](https://github.com/mrnabati/CenterFusion/assets/79453927/681c580e-3222-4732-a7c9-77d6eb71a378)

**Comment by Manishnayak234** [comment]
They are removed bro!

**Comment by umar052001** [comment]
> They are removed bro!

Shouldn't they mention that in the Readme rather then giving links.

**Comment by weisha1991** [comment]
So who has the latest link for download?
