### ISSUE TITLE
how to run demo.py?

### ISSUE THREAD

**Issue by vincentzhouwenqi** [mrnabati/CenterFusion#9]
i want to run demo.py for video detection by using centerfusion_e60.pth.
what should i do in terminal.

**Comment by vincentzhouwenqi** [comment]
i run with this commend 

`python demo.py ctdet --demo /home/vincent/CenterFusion/data/nuscenes/samples/CAM_FRONT/ --load_model /home/vincent/CenterFusion/models/centerfusion_e60.pth`

but there is an error occored:

Traceback (most recent call last):
  File "demo.py", line 124, in <module>
    demo(opt)
  File "demo.py", line 95, in demo
    ret = detector.run(image_name)
  File "/home/vincent/CenterFusion/src/lib/detector.py", line 136, in run
    results = self.merge_outputs(detections)
  File "/home/vincent/CenterFusion/src/lib/detector.py", line 362, in merge_outputs
    if det['score'] > self.opt.out_thresh and all(det['dim'] > 0):
KeyError: 'dim'

**Comment by mrnabati** [comment]
Sorry but the demo is not currently supported. It needs some modifications to work with the CenterFusion model and I haven't gotten a chance to fix it yet.

**Comment by nguyenhuykhang** [comment]
Hello, if possible, can you share me with the  centerfusion_e60.pth checkpoint, the checkpoint link is expired
